2016/08/17 08:32:16 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1049] Unknown database 'testdrive'' in C:\xampp\htdocs\yii\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\yii\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\yii\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\yii\framework\base\CModule.php(103): CModule->getComponent('db')
#4 C:\xampp\htdocs\yii\framework\gii\generators\crud\CrudCode.php(44): CModule->__get('db')
#5 C:\xampp\htdocs\yii\framework\web\CFormModel.php(39): CrudCode->init()
#6 C:\xampp\htdocs\yii\framework\gii\CCodeGenerator.php(153): CFormModel->__construct()
#7 C:\xampp\htdocs\yii\framework\gii\CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('index')
#13 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/crud/index')
#14 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#15 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yiitest/index.php?r=gii/crud/index
HTTP_REFERER=http://localhost/yiitest/index.php?r=gii/default/index
---
2016/08/17 08:34:48 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'testdrive.tbl_user' doesn't exist. The SQL statement executed was: SHOW FULL COLUMNS FROM `tbl_user`.
in C:\xampp\htdocs\yiitest\index.php (13)
2016/08/17 08:37:50 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "user".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=user
---
2016/08/17 08:38:20 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "tbl_user".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('tbl_user')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php?r=tbl_user
---
2016/08/17 08:47:53 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "test".' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('test')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('test')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/test')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/yiitest/index.php?r=site/test
HTTP_REFERER=http://localhost/yiitest/index.php?r=tblUser
---
2016/08/17 08:49:05 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "test".' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('test')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('test')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/test')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/yiitest/index.php?r=site/test
HTTP_REFERER=http://localhost/yiitest/index.php?r=tblUser
---
2016/08/17 08:50:08 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "test".' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('test')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('test')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/test')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/yiitest/index.php?r=site/test
HTTP_REFERER=http://localhost/yiitest/index.php?r=tblUser
---
2016/08/17 08:51:15 [error] [php] Undefined variable: model (C:\xampp\htdocs\yiitest\protected\controllers\SiteController.php:114)
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(286): SiteController->runAction()
#1 C:\xampp\htdocs\yii\framework\web\CController.php(265): SiteController->runActionWithFilters()
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): SiteController->run()
#3 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#4 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#5 C:\xampp\htdocs\yiitest\index.php(13): CWebApplication->run()
REQUEST_URI=/yiitest/index.php?r=site/test
in C:\xampp\htdocs\yiitest\protected\controllers\SiteController.php (114)
in C:\xampp\htdocs\yiitest\index.php (13)
2016/08/17 08:51:26 [error] [php] Undefined variable: model (C:\xampp\htdocs\yiitest\protected\controllers\SiteController.php:114)
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(286): SiteController->runAction()
#1 C:\xampp\htdocs\yii\framework\web\CController.php(265): SiteController->runActionWithFilters()
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): SiteController->run()
#3 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#4 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#5 C:\xampp\htdocs\yiitest\index.php(13): CWebApplication->run()
REQUEST_URI=/yiitest/index.php?r=site/test
in C:\xampp\htdocs\yiitest\protected\controllers\SiteController.php (114)
in C:\xampp\htdocs\yiitest\index.php (13)
2016/08/17 10:41:00 [error] [exception.CDbException] exception 'CDbException' with message 'Table "tbl_skill" does not have a column named "username".' in C:\xampp\htdocs\yii\framework\db\schema\CDbCommandBuilder.php:697
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(1523): CDbCommandBuilder->createColumnCriteria(Object(CMysqlTableSchema), Array, '', Array, '`t`.')
#1 C:\xampp\htdocs\yiitest\protected\components\UserIdentity.php(26): CActiveRecord->findByAttributes(Array)
#2 C:\xampp\htdocs\yiitest\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#3 C:\xampp\htdocs\yii\framework\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#4 C:\xampp\htdocs\yii\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#5 C:\xampp\htdocs\yii\framework\base\CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#6 C:\xampp\htdocs\yiitest\protected\controllers\SiteController.php(106): CModel->validate()
#7 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#8 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#9 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#10 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('login')
#12 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#13 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#14 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/yiitest/index.php?r=site/login
HTTP_REFERER=http://localhost/yiitest/index.php?r=site/login
---
2016/08/17 10:46:07 [error] [php] Undefined variable: record (C:\xampp\htdocs\yiitest\protected\components\UserIdentity.php:23)
Stack trace:
#0 C:\xampp\htdocs\yii\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute()
#1 C:\xampp\htdocs\yii\framework\base\CModel.php(159): CInlineValidator->validate()
#2 C:\xampp\htdocs\yiitest\protected\controllers\SiteController.php(106): LoginForm->validate()
#3 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#4 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#5 C:\xampp\htdocs\yii\framework\web\CController.php(286): SiteController->runAction()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(265): SiteController->runActionWithFilters()
#7 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): SiteController->run()
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\yiitest\index.php(13): CWebApplication->run()
REQUEST_URI=/yiitest/index.php?r=site/login
in C:\xampp\htdocs\yiitest\protected\components\UserIdentity.php (23)
in C:\xampp\htdocs\yiitest\protected\models\LoginForm.php (52)
in C:\xampp\htdocs\yiitest\protected\controllers\SiteController.php (106)
2016/08/17 10:59:48 [error] [php] Undefined variable: record (C:\xampp\htdocs\yiitest\protected\components\UserIdentity.php:28)
Stack trace:
#0 C:\xampp\htdocs\yii\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute()
#1 C:\xampp\htdocs\yii\framework\base\CModel.php(159): CInlineValidator->validate()
#2 C:\xampp\htdocs\yiitest\protected\controllers\SiteController.php(106): LoginForm->validate()
#3 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#4 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#5 C:\xampp\htdocs\yii\framework\web\CController.php(286): SiteController->runAction()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(265): SiteController->runActionWithFilters()
#7 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): SiteController->run()
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\yiitest\index.php(13): CWebApplication->run()
REQUEST_URI=/yiitest/index.php?r=site/login
in C:\xampp\htdocs\yiitest\protected\components\UserIdentity.php (28)
in C:\xampp\htdocs\yiitest\protected\models\LoginForm.php (52)
in C:\xampp\htdocs\yiitest\protected\controllers\SiteController.php (106)
2016/08/17 11:01:07 [error] [php] Undefined variable: record (C:\xampp\htdocs\yiitest\protected\components\UserIdentity.php:29)
Stack trace:
#0 C:\xampp\htdocs\yii\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute()
#1 C:\xampp\htdocs\yii\framework\base\CModel.php(159): CInlineValidator->validate()
#2 C:\xampp\htdocs\yiitest\protected\controllers\SiteController.php(106): LoginForm->validate()
#3 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#4 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#5 C:\xampp\htdocs\yii\framework\web\CController.php(286): SiteController->runAction()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(265): SiteController->runActionWithFilters()
#7 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): SiteController->run()
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\yiitest\index.php(13): CWebApplication->run()
REQUEST_URI=/yiitest/index.php?r=site/login
in C:\xampp\htdocs\yiitest\protected\components\UserIdentity.php (29)
in C:\xampp\htdocs\yiitest\protected\models\LoginForm.php (52)
in C:\xampp\htdocs\yiitest\protected\controllers\SiteController.php (106)
2016/08/17 11:01:14 [error] [exception.CException] exception 'CException' with message 'Property "TblUser.title" is not defined.' in C:\xampp\htdocs\yii\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(145): CComponent->__get('title')
#1 C:\xampp\htdocs\yiitest\protected\components\UserIdentity.php(29): CActiveRecord->__get('title')
#2 C:\xampp\htdocs\yiitest\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#3 C:\xampp\htdocs\yii\framework\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#4 C:\xampp\htdocs\yii\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#5 C:\xampp\htdocs\yii\framework\base\CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#6 C:\xampp\htdocs\yiitest\protected\controllers\SiteController.php(106): CModel->validate()
#7 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#8 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#9 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#10 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('login')
#12 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#13 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#14 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/yiitest/index.php?r=site/login
HTTP_REFERER=http://localhost/yiitest/index.php?r=site/login
---
2016/08/17 15:35:18 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('')
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('tblUser')
#9 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/yiitest/index.php?r=tblUser
---
2016/08/17 15:46:53 [error] [php] Trying to get property of non-object (C:\xampp\htdocs\yiitest\protected\views\tblSkill\index.php:17)
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(869): TblSkillController->renderFile()
#1 C:\xampp\htdocs\yii\framework\web\CController.php(782): TblSkillController->renderPartial()
#2 C:\xampp\htdocs\yiitest\protected\controllers\TblSkillController.php(131): TblSkillController->render()
#3 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): TblSkillController->actionIndex()
#4 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#5 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): TblSkillController->runAction()
#6 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#7 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CAccessControlFilter->filter()
#8 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): TblSkillController->filterAccessControl()
#9 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#10 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#11 C:\xampp\htdocs\yii\framework\web\CController.php(265): TblSkillController->runActionWithFilters()
#12 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): TblSkillController->run()
#13 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#14 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#15 C:\xampp\htdocs\yiitest\index.php(13): CWebApplication->run()
REQUEST_URI=/yiitest/index.php?r=tblSkill/index
in C:\xampp\htdocs\yiitest\protected\views\tblSkill\index.php (17)
in C:\xampp\htdocs\yiitest\protected\controllers\TblSkillController.php (131)
in C:\xampp\htdocs\yiitest\index.php (13)
2016/08/17 16:23:55 [error] [exception.CDbException] exception 'CDbException' with message 'The relation "userSkill_skill" in active record class "TblUserSkill" is specified with an incomplete foreign key. The foreign key must consist of columns referencing both joining tables.' in C:\xampp\htdocs\yii\framework\db\ar\CActiveFinder.php:1214
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\ar\CActiveFinder.php(1043): CJoinElement->joinManyMany(Object(CMysqlTableSchema), Array, Object(CJoinElement))
#1 C:\xampp\htdocs\yii\framework\db\ar\CActiveFinder.php(1317): CJoinElement->getJoinCondition()
#2 C:\xampp\htdocs\yii\framework\db\ar\CActiveFinder.php(795): CJoinQuery->join(Object(CJoinElement))
#3 C:\xampp\htdocs\yii\framework\db\ar\CActiveFinder.php(438): CJoinElement->buildQuery(Object(CJoinQuery))
#4 C:\xampp\htdocs\yii\framework\db\ar\CActiveFinder.php(68): CJoinElement->find(Object(CDbCriteria))
#5 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(1361): CActiveFinder->query(Object(CDbCriteria), true)
#6 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(1475): CActiveRecord->query(Object(CDbCriteria), true)
#7 C:\xampp\htdocs\yiitest\protected\controllers\TblSkillController.php(128): CActiveRecord->findAll()
#8 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): TblSkillController->actionIndex()
#9 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#11 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#12 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#13 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#14 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#15 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#16 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#17 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('index')
#18 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('tblSkill/index')
#19 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#20 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#21 {main}
REQUEST_URI=/yiitest/index.php?r=tblSkill/index
HTTP_REFERER=http://localhost/yiitest/index.php?r=site/login
---
2016/08/17 16:24:40 [error] [exception.CDbException] exception 'CDbException' with message 'The relation "userSkill_skill" in active record class "TblUserSkill" is specified with an incomplete foreign key. The foreign key must consist of columns referencing both joining tables.' in C:\xampp\htdocs\yii\framework\db\ar\CActiveFinder.php:1214
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\ar\CActiveFinder.php(1043): CJoinElement->joinManyMany(Object(CMysqlTableSchema), Array, Object(CJoinElement))
#1 C:\xampp\htdocs\yii\framework\db\ar\CActiveFinder.php(1317): CJoinElement->getJoinCondition()
#2 C:\xampp\htdocs\yii\framework\db\ar\CActiveFinder.php(795): CJoinQuery->join(Object(CJoinElement))
#3 C:\xampp\htdocs\yii\framework\db\ar\CActiveFinder.php(438): CJoinElement->buildQuery(Object(CJoinQuery))
#4 C:\xampp\htdocs\yii\framework\db\ar\CActiveFinder.php(68): CJoinElement->find(Object(CDbCriteria))
#5 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(1361): CActiveFinder->query(Object(CDbCriteria), true)
#6 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(1475): CActiveRecord->query(Object(CDbCriteria), true)
#7 C:\xampp\htdocs\yiitest\protected\controllers\TblSkillController.php(128): CActiveRecord->findAll()
#8 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): TblSkillController->actionIndex()
#9 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#11 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#12 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#13 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#14 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#15 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#16 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#17 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('index')
#18 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('tblSkill/index')
#19 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#20 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#21 {main}
REQUEST_URI=/yiitest/index.php?r=tblSkill/index
HTTP_REFERER=http://localhost/yiitest/index.php?r=site/login
---
2016/08/17 16:25:01 [error] [exception.CDbException] exception 'CDbException' with message 'The relation "userSkill_skill" in active record class "TblUserSkill" is specified with an incomplete foreign key. The foreign key must consist of columns referencing both joining tables.' in C:\xampp\htdocs\yii\framework\db\ar\CActiveFinder.php:1214
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\ar\CActiveFinder.php(1043): CJoinElement->joinManyMany(Object(CMysqlTableSchema), Array, Object(CJoinElement))
#1 C:\xampp\htdocs\yii\framework\db\ar\CActiveFinder.php(1317): CJoinElement->getJoinCondition()
#2 C:\xampp\htdocs\yii\framework\db\ar\CActiveFinder.php(795): CJoinQuery->join(Object(CJoinElement))
#3 C:\xampp\htdocs\yii\framework\db\ar\CActiveFinder.php(438): CJoinElement->buildQuery(Object(CJoinQuery))
#4 C:\xampp\htdocs\yii\framework\db\ar\CActiveFinder.php(68): CJoinElement->find(Object(CDbCriteria))
#5 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(1361): CActiveFinder->query(Object(CDbCriteria), true)
#6 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(1475): CActiveRecord->query(Object(CDbCriteria), true)
#7 C:\xampp\htdocs\yiitest\protected\controllers\TblSkillController.php(128): CActiveRecord->findAll()
#8 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): TblSkillController->actionIndex()
#9 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#11 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#12 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#13 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#14 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#15 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#16 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#17 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('index')
#18 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('tblSkill/index')
#19 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#20 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#21 {main}
REQUEST_URI=/yiitest/index.php?r=tblSkill/index
HTTP_REFERER=http://localhost/yiitest/index.php?r=site/login
---
2016/08/17 16:26:20 [error] [exception.CDbException] exception 'CDbException' with message 'Relation "userSkill_skill" is not defined in active record class "TblUserSkill".' in C:\xampp\htdocs\yii\framework\db\ar\CActiveFinder.php:226
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\ar\CActiveFinder.php(299): CActiveFinder->buildJoinTree(Object(CJoinElement), 'userSkill_skill')
#1 C:\xampp\htdocs\yii\framework\db\ar\CActiveFinder.php(48): CActiveFinder->buildJoinTree(Object(CJoinElement), Array)
#2 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(912): CActiveFinder->__construct(Object(TblUserSkill), Array)
#3 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(1360): CActiveRecord->getActiveFinder(Array)
#4 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(1475): CActiveRecord->query(Object(CDbCriteria), true)
#5 C:\xampp\htdocs\yiitest\protected\controllers\TblSkillController.php(128): CActiveRecord->findAll()
#6 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): TblSkillController->actionIndex()
#7 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#8 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#9 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#10 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#11 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#12 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#13 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#14 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#15 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('index')
#16 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('tblSkill/index')
#17 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#18 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#19 {main}
REQUEST_URI=/yiitest/index.php?r=tblSkill/index
HTTP_REFERER=http://localhost/yiitest/index.php?r=site/login
---
2016/08/17 16:26:34 [error] [exception.CDbException] exception 'CDbException' with message 'The relation "userSkill_skill" in active record class "TblUserSkill" is specified with an incomplete foreign key. The foreign key must consist of columns referencing both joining tables.' in C:\xampp\htdocs\yii\framework\db\ar\CActiveFinder.php:1214
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\ar\CActiveFinder.php(1043): CJoinElement->joinManyMany(Object(CMysqlTableSchema), Array, Object(CJoinElement))
#1 C:\xampp\htdocs\yii\framework\db\ar\CActiveFinder.php(1317): CJoinElement->getJoinCondition()
#2 C:\xampp\htdocs\yii\framework\db\ar\CActiveFinder.php(795): CJoinQuery->join(Object(CJoinElement))
#3 C:\xampp\htdocs\yii\framework\db\ar\CActiveFinder.php(438): CJoinElement->buildQuery(Object(CJoinQuery))
#4 C:\xampp\htdocs\yii\framework\db\ar\CActiveFinder.php(68): CJoinElement->find(Object(CDbCriteria))
#5 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(1361): CActiveFinder->query(Object(CDbCriteria), true)
#6 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(1475): CActiveRecord->query(Object(CDbCriteria), true)
#7 C:\xampp\htdocs\yiitest\protected\controllers\TblSkillController.php(128): CActiveRecord->findAll()
#8 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): TblSkillController->actionIndex()
#9 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#11 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#12 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#13 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#14 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#15 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#16 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#17 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('index')
#18 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('tblSkill/index')
#19 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#20 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#21 {main}
REQUEST_URI=/yiitest/index.php?r=tblSkill/index
HTTP_REFERER=http://localhost/yiitest/index.php?r=site/login
---
2016/08/17 16:26:48 [error] [exception.CDbException] exception 'CDbException' with message 'The relation "userSkill_skill" in active record class "TblUserSkill" is specified with an incomplete foreign key. The foreign key must consist of columns referencing both joining tables.' in C:\xampp\htdocs\yii\framework\db\ar\CActiveFinder.php:1214
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\ar\CActiveFinder.php(1043): CJoinElement->joinManyMany(Object(CMysqlTableSchema), Array, Object(CJoinElement))
#1 C:\xampp\htdocs\yii\framework\db\ar\CActiveFinder.php(1317): CJoinElement->getJoinCondition()
#2 C:\xampp\htdocs\yii\framework\db\ar\CActiveFinder.php(795): CJoinQuery->join(Object(CJoinElement))
#3 C:\xampp\htdocs\yii\framework\db\ar\CActiveFinder.php(438): CJoinElement->buildQuery(Object(CJoinQuery))
#4 C:\xampp\htdocs\yii\framework\db\ar\CActiveFinder.php(68): CJoinElement->find(Object(CDbCriteria))
#5 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(1361): CActiveFinder->query(Object(CDbCriteria), true)
#6 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(1475): CActiveRecord->query(Object(CDbCriteria), true)
#7 C:\xampp\htdocs\yiitest\protected\controllers\TblSkillController.php(128): CActiveRecord->findAll()
#8 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): TblSkillController->actionIndex()
#9 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#11 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#12 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#13 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#14 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#15 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#16 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#17 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('index')
#18 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('tblSkill/index')
#19 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#20 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#21 {main}
REQUEST_URI=/yiitest/index.php?r=tblSkill/index
HTTP_REFERER=http://localhost/yiitest/index.php?r=site/login
---
2016/08/17 16:37:19 [error] [exception.CDbException] exception 'CDbException' with message 'Relation "TblUserSkill" is not defined in active record class "TblUserSkill".' in C:\xampp\htdocs\yii\framework\db\ar\CActiveFinder.php:226
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\ar\CActiveFinder.php(299): CActiveFinder->buildJoinTree(Object(CJoinElement), 'TblUserSkill')
#1 C:\xampp\htdocs\yii\framework\db\ar\CActiveFinder.php(48): CActiveFinder->buildJoinTree(Object(CJoinElement), Array)
#2 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(912): CActiveFinder->__construct(Object(TblUserSkill), Array)
#3 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(1360): CActiveRecord->getActiveFinder(Array)
#4 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(1475): CActiveRecord->query(Object(CDbCriteria), true)
#5 C:\xampp\htdocs\yiitest\protected\controllers\TblSkillController.php(128): CActiveRecord->findAll()
#6 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): TblSkillController->actionIndex()
#7 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#8 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#9 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#10 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#11 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#12 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#13 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#14 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#15 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('index')
#16 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('tblSkill/index')
#17 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#18 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#19 {main}
REQUEST_URI=/yiitest/index.php?r=tblSkill/index
HTTP_REFERER=http://localhost/yiitest/index.php?r=site/login
---
2016/08/17 16:39:13 [error] [php] Undefined variable: id (C:\xampp\htdocs\yiitest\protected\controllers\TblSkillController.php:125)
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): TblSkillController->runAction()
#1 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#2 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CAccessControlFilter->filter()
#3 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): TblSkillController->filterAccessControl()
#4 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#5 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(265): TblSkillController->runActionWithFilters()
#7 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): TblSkillController->run()
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\yiitest\index.php(13): CWebApplication->run()
REQUEST_URI=/yiitest/index.php?r=tblSkill/index
in C:\xampp\htdocs\yiitest\protected\controllers\TblSkillController.php (125)
in C:\xampp\htdocs\yiitest\index.php (13)
2016/08/17 16:49:38 [error] [exception.CException] exception 'CException' with message 'Property "CDbCriteria.user_id" is not defined.' in C:\xampp\htdocs\yii\framework\base\CComponent.php:173
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\schema\CDbCriteria.php(160): CComponent->__set('user_id', '1')
#1 C:\xampp\htdocs\yii\framework\db\schema\CDbCommandBuilder.php(588): CDbCriteria->__construct(Array)
#2 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(1474): CDbCommandBuilder->createCriteria(Array, Array)
#3 C:\xampp\htdocs\yiitest\protected\controllers\TblSkillController.php(131): CActiveRecord->findAll(Array)
#4 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): TblSkillController->actionIndex()
#5 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#6 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#7 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#8 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#9 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#10 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#11 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#12 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#13 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('index')
#14 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('tblSkill/index')
#15 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#16 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#17 {main}
REQUEST_URI=/yiitest/index.php?r=tblSkill/index
HTTP_REFERER=http://localhost/yiitest/index.php?r=site/login
---
2016/08/17 16:49:46 [error] [php] Undefined index: skill_id (C:\xampp\htdocs\yiitest\protected\views\tblSkill\index.php:27)
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(869): TblSkillController->renderFile()
#1 C:\xampp\htdocs\yii\framework\web\CController.php(782): TblSkillController->renderPartial()
#2 C:\xampp\htdocs\yiitest\protected\controllers\TblSkillController.php(139): TblSkillController->render()
#3 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): TblSkillController->actionIndex()
#4 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#5 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): TblSkillController->runAction()
#6 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#7 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CAccessControlFilter->filter()
#8 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): TblSkillController->filterAccessControl()
#9 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#10 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#11 C:\xampp\htdocs\yii\framework\web\CController.php(265): TblSkillController->runActionWithFilters()
#12 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): TblSkillController->run()
#13 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#14 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#15 C:\xampp\htdocs\yiitest\index.php(13): CWebApplication->run()
REQUEST_URI=/yiitest/index.php?r=tblSkill/index
in C:\xampp\htdocs\yiitest\protected\views\tblSkill\index.php (27)
in C:\xampp\htdocs\yiitest\protected\controllers\TblSkillController.php (139)
in C:\xampp\htdocs\yiitest\index.php (13)
2016/08/17 16:53:28 [error] [php] Undefined index: skill_id (C:\xampp\htdocs\yiitest\protected\views\tblSkill\index.php:27)
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(869): TblSkillController->renderFile()
#1 C:\xampp\htdocs\yii\framework\web\CController.php(782): TblSkillController->renderPartial()
#2 C:\xampp\htdocs\yiitest\protected\controllers\TblSkillController.php(132): TblSkillController->render()
#3 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): TblSkillController->actionIndex()
#4 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#5 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): TblSkillController->runAction()
#6 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#7 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CAccessControlFilter->filter()
#8 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): TblSkillController->filterAccessControl()
#9 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#10 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#11 C:\xampp\htdocs\yii\framework\web\CController.php(265): TblSkillController->runActionWithFilters()
#12 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): TblSkillController->run()
#13 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#14 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#15 C:\xampp\htdocs\yiitest\index.php(13): CWebApplication->run()
REQUEST_URI=/yiitest/index.php?r=tblSkill/index
in C:\xampp\htdocs\yiitest\protected\views\tblSkill\index.php (27)
in C:\xampp\htdocs\yiitest\protected\controllers\TblSkillController.php (132)
in C:\xampp\htdocs\yiitest\index.php (13)
2016/08/17 16:55:34 [error] [exception.CDbException] exception 'CDbException' with message 'The relation "TblSkill" in active record class "TblUserSkill" is specified with an invalid foreign key "skill_id". There is no such column in the table "tbl_skill".' in C:\xampp\htdocs\yii\framework\db\ar\CActiveFinder.php:1101
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\ar\CActiveFinder.php(1072): CJoinElement->joinOneMany(Object(CJoinElement), Array, Object(CJoinElement), Object(CJoinElement))
#1 C:\xampp\htdocs\yii\framework\db\ar\CActiveFinder.php(1317): CJoinElement->getJoinCondition()
#2 C:\xampp\htdocs\yii\framework\db\ar\CActiveFinder.php(795): CJoinQuery->join(Object(CJoinElement))
#3 C:\xampp\htdocs\yii\framework\db\ar\CActiveFinder.php(438): CJoinElement->buildQuery(Object(CJoinQuery))
#4 C:\xampp\htdocs\yii\framework\db\ar\CActiveFinder.php(68): CJoinElement->find(Object(CDbCriteria))
#5 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(1361): CActiveFinder->query(Object(CDbCriteria), true)
#6 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(1541): CActiveRecord->query(Object(CDbCriteria), true)
#7 C:\xampp\htdocs\yiitest\protected\controllers\TblSkillController.php(128): CActiveRecord->findAllByAttributes(Array)
#8 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): TblSkillController->actionIndex()
#9 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#11 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#12 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#13 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#14 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#15 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#16 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#17 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('index')
#18 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('tblSkill/index')
#19 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#20 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#21 {main}
REQUEST_URI=/yiitest/index.php?r=tblSkill/index
HTTP_REFERER=http://localhost/yiitest/index.php?r=site/login
---
2016/08/17 17:07:57 [error] [system.db.CDbCommand] CDbCommand::fetch() failed: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '}' at line 1. The SQL statement executed was: Select * from tbl_user_skill where user_id = {$userID}.
in C:\xampp\htdocs\yiitest\protected\models\TblUserSkill.php (89)
in C:\xampp\htdocs\yiitest\protected\controllers\TblSkillController.php (129)
in C:\xampp\htdocs\yiitest\index.php (13)
2016/08/17 17:07:57 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '}' at line 1. The SQL statement executed was: Select * from tbl_user_skill where user_id = {$userID}' in C:\xampp\htdocs\yii\framework\db\CDbCommand.php:543
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\CDbCommand.php(415): CDbCommand->queryInternal('fetch', Array, Array)
#1 C:\xampp\htdocs\yiitest\protected\models\TblUserSkill.php(89): CDbCommand->queryRow()
#2 C:\xampp\htdocs\yiitest\protected\controllers\TblSkillController.php(129): TblUserSkill->getData('f0112057')
#3 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): TblSkillController->actionIndex()
#4 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#6 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#7 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#8 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#9 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#10 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#11 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('index')
#13 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('tblSkill/index')
#14 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#15 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yiitest/index.php?r=tblSkill/index
HTTP_REFERER=http://localhost/yiitest/index.php?r=site/login
---
2016/08/17 17:14:24 [error] [system.db.CDbCommand] CDbCommand::fetch() failed: SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'id' in where clause is ambiguous. The SQL statement executed was: SELECT *
FROM `tbl_user_skill` `us`
JOIN `tbl_skill` `s` ON s.id=us.user_id
WHERE id=:id.
in C:\xampp\htdocs\yiitest\protected\models\TblUserSkill.php (93)
in C:\xampp\htdocs\yiitest\protected\controllers\TblSkillController.php (129)
in C:\xampp\htdocs\yiitest\index.php (13)
2016/08/17 17:14:24 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'id' in where clause is ambiguous. The SQL statement executed was: SELECT *
FROM `tbl_user_skill` `us`
JOIN `tbl_skill` `s` ON s.id=us.user_id
WHERE id=:id' in C:\xampp\htdocs\yii\framework\db\CDbCommand.php:543
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\CDbCommand.php(415): CDbCommand->queryInternal('fetch', Array, Array)
#1 C:\xampp\htdocs\yiitest\protected\models\TblUserSkill.php(93): CDbCommand->queryRow()
#2 C:\xampp\htdocs\yiitest\protected\controllers\TblSkillController.php(129): TblUserSkill->getData('1')
#3 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): TblSkillController->actionIndex()
#4 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#6 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#7 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#8 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#9 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#10 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#11 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('index')
#13 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('tblSkill/index')
#14 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#15 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yiitest/index.php?r=tblSkill/index
HTTP_REFERER=http://localhost/yiitest/index.php?r=site/login
---
2016/08/17 17:15:17 [error] [system.db.CDbCommand] CDbCommand::fetch() failed: SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'id' in where clause is ambiguous. The SQL statement executed was: SELECT *
FROM `tbl_user_skill` `us`
JOIN `tbl_skill` ON tbl_skill.id=us.user_id
WHERE id=:id.
in C:\xampp\htdocs\yiitest\protected\models\TblUserSkill.php (93)
in C:\xampp\htdocs\yiitest\protected\controllers\TblSkillController.php (129)
in C:\xampp\htdocs\yiitest\index.php (13)
2016/08/17 17:15:17 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'id' in where clause is ambiguous. The SQL statement executed was: SELECT *
FROM `tbl_user_skill` `us`
JOIN `tbl_skill` ON tbl_skill.id=us.user_id
WHERE id=:id' in C:\xampp\htdocs\yii\framework\db\CDbCommand.php:543
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\CDbCommand.php(415): CDbCommand->queryInternal('fetch', Array, Array)
#1 C:\xampp\htdocs\yiitest\protected\models\TblUserSkill.php(93): CDbCommand->queryRow()
#2 C:\xampp\htdocs\yiitest\protected\controllers\TblSkillController.php(129): TblUserSkill->getData('1')
#3 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): TblSkillController->actionIndex()
#4 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#6 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#7 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#8 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#9 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#10 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#11 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('index')
#13 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('tblSkill/index')
#14 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#15 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yiitest/index.php?r=tblSkill/index
HTTP_REFERER=http://localhost/yiitest/index.php?r=site/login
---
2016/08/17 17:23:07 [error] [exception.CException] exception 'CException' with message 'CDbCommand and its behaviors do not have a method or closure named "queryRows".' in C:\xampp\htdocs\yii\framework\base\CComponent.php:266
Stack trace:
#0 C:\xampp\htdocs\yiitest\protected\models\TblUserSkill.php(92): CComponent->__call('queryRows', Array)
#1 C:\xampp\htdocs\yiitest\protected\models\TblUserSkill.php(92): CDbCommand->queryRows()
#2 C:\xampp\htdocs\yiitest\protected\controllers\TblSkillController.php(129): TblUserSkill->getData('1')
#3 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): TblSkillController->actionIndex()
#4 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#6 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#7 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#8 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#9 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#10 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#11 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('index')
#13 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('tblSkill/index')
#14 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#15 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yiitest/index.php?r=tblSkill/index
HTTP_REFERER=http://localhost/yiitest/index.php?r=site/login
---
2016/08/17 17:49:38 [error] [exception.CException] exception 'CException' with message 'TblSkill and its behaviors do not have a method or closure named "getSkillNotOfUser".' in C:\xampp\htdocs\yii\framework\base\CComponent.php:266
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(227): CComponent->__call('getSkillNotOfUs...', Array)
#1 C:\xampp\htdocs\yiitest\protected\controllers\TblSkillController.php(127): CActiveRecord->__call('getSkillNotOfUs...', Array)
#2 C:\xampp\htdocs\yiitest\protected\controllers\TblSkillController.php(127): TblSkill->getSkillNotOfUser()
#3 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): TblSkillController->actionIndex()
#4 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#6 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#7 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#8 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#9 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#10 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#11 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('index')
#13 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('tblSkill/index')
#14 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#15 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yiitest/index.php?r=tblSkill/index
HTTP_REFERER=http://localhost/yiitest/index.php?r=site/login
---
2016/08/17 17:49:54 [error] [exception.CException] exception 'CException' with message 'TblSkill and its behaviors do not have a method or closure named "getSkillNotOfUser".' in C:\xampp\htdocs\yii\framework\base\CComponent.php:266
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(227): CComponent->__call('getSkillNotOfUs...', Array)
#1 C:\xampp\htdocs\yiitest\protected\controllers\TblSkillController.php(127): CActiveRecord->__call('getSkillNotOfUs...', Array)
#2 C:\xampp\htdocs\yiitest\protected\controllers\TblSkillController.php(127): TblSkill->getSkillNotOfUser()
#3 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): TblSkillController->actionIndex()
#4 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#6 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#7 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#8 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#9 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#10 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#11 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('index')
#13 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('tblSkill/index')
#14 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#15 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yiitest/index.php?r=tblSkill/index
HTTP_REFERER=http://localhost/yiitest/index.php?r=site/login
---
2016/08/17 17:50:16 [error] [exception.CException] exception 'CException' with message 'TblSkill and its behaviors do not have a method or closure named "getSkillNotOfUser".' in C:\xampp\htdocs\yii\framework\base\CComponent.php:266
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(227): CComponent->__call('getSkillNotOfUs...', Array)
#1 C:\xampp\htdocs\yiitest\protected\controllers\TblSkillController.php(128): CActiveRecord->__call('getSkillNotOfUs...', Array)
#2 C:\xampp\htdocs\yiitest\protected\controllers\TblSkillController.php(128): TblSkill->getSkillNotOfUser('1')
#3 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): TblSkillController->actionIndex()
#4 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#6 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#7 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#8 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#9 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#10 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#11 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('index')
#13 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('tblSkill/index')
#14 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#15 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yiitest/index.php?r=tblSkill/index
HTTP_REFERER=http://localhost/yiitest/index.php?r=site/login
---
2016/08/17 17:52:53 [error] [exception.CException] exception 'CException' with message 'CDbCommand and its behaviors do not have a method or closure named "outerjoin".' in C:\xampp\htdocs\yii\framework\base\CComponent.php:266
Stack trace:
#0 C:\xampp\htdocs\yiitest\protected\models\TblSkill.php(90): CComponent->__call('outerjoin', Array)
#1 C:\xampp\htdocs\yiitest\protected\models\TblSkill.php(90): CDbCommand->outerjoin('tbl_user_skill ...', 's.id=us.skill_i...')
#2 C:\xampp\htdocs\yiitest\protected\controllers\TblSkillController.php(128): TblSkill->getSkillNotOfUser('1')
#3 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): TblSkillController->actionIndex()
#4 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#6 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#7 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#8 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#9 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#10 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#11 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('index')
#13 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('tblSkill/index')
#14 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#15 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yiitest/index.php?r=tblSkill/index
HTTP_REFERER=http://localhost/yiitest/index.php?r=site/login
---
2016/08/17 17:56:41 [error] [exception.CException] exception 'CException' with message 'CDbCommand and its behaviors do not have a method or closure named "leftouterjoin".' in C:\xampp\htdocs\yii\framework\base\CComponent.php:266
Stack trace:
#0 C:\xampp\htdocs\yiitest\protected\models\TblSkill.php(90): CComponent->__call('leftouterjoin', Array)
#1 C:\xampp\htdocs\yiitest\protected\models\TblSkill.php(90): CDbCommand->leftouterjoin('tbl_user_skill ...', 's.id=us.skill_i...')
#2 C:\xampp\htdocs\yiitest\protected\controllers\TblSkillController.php(128): TblSkill->getSkillNotOfUser('1')
#3 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): TblSkillController->actionIndex()
#4 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#6 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#7 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#8 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#9 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#10 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#11 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('index')
#13 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('tblSkill/index')
#14 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#15 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yiitest/index.php?r=tblSkill/index
HTTP_REFERER=http://localhost/yiitest/index.php?r=site/login
---
2016/08/17 18:07:14 [error] [php] Trying to get property of non-object (C:\xampp\htdocs\yiitest\protected\views\tblSkill\index.php:17)
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(869): TblSkillController->renderFile()
#1 C:\xampp\htdocs\yii\framework\web\CController.php(782): TblSkillController->renderPartial()
#2 C:\xampp\htdocs\yiitest\protected\controllers\TblSkillController.php(133): TblSkillController->render()
#3 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): TblSkillController->actionIndex()
#4 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#5 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): TblSkillController->runAction()
#6 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#7 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CAccessControlFilter->filter()
#8 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): TblSkillController->filterAccessControl()
#9 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#10 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#11 C:\xampp\htdocs\yii\framework\web\CController.php(265): TblSkillController->runActionWithFilters()
#12 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): TblSkillController->run()
#13 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#14 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#15 C:\xampp\htdocs\yiitest\index.php(13): CWebApplication->run()
REQUEST_URI=/yiitest/index.php?r=tblSkill/index
in C:\xampp\htdocs\yiitest\protected\views\tblSkill\index.php (17)
in C:\xampp\htdocs\yiitest\protected\controllers\TblSkillController.php (133)
in C:\xampp\htdocs\yiitest\index.php (13)
2016/08/17 18:19:54 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'tbl_user_skill.skill_id' in 'where clause'. The SQL statement executed was: SELECT *
FROM `tbl_skill` `s`
LEFT JOIN `tbl_user_skill` `us` ON s.id=us.skill_id
WHERE tbl_user_skill.skill_id IS NULL.
in C:\xampp\htdocs\yiitest\protected\models\TblSkill.php (92)
in C:\xampp\htdocs\yiitest\protected\controllers\TblSkillController.php (128)
in C:\xampp\htdocs\yiitest\index.php (13)
2016/08/17 18:19:54 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'tbl_user_skill.skill_id' in 'where clause'. The SQL statement executed was: SELECT *
FROM `tbl_skill` `s`
LEFT JOIN `tbl_user_skill` `us` ON s.id=us.skill_id
WHERE tbl_user_skill.skill_id IS NULL' in C:\xampp\htdocs\yii\framework\db\CDbCommand.php:543
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\CDbCommand.php(396): CDbCommand->queryInternal('fetchAll', Array, Array)
#1 C:\xampp\htdocs\yiitest\protected\models\TblSkill.php(92): CDbCommand->queryAll()
#2 C:\xampp\htdocs\yiitest\protected\controllers\TblSkillController.php(128): TblSkill->getSkillNotOfUser()
#3 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): TblSkillController->actionIndex()
#4 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#6 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#7 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#8 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#9 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#10 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#11 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('index')
#13 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('tblSkill/index')
#14 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#15 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yiitest/index.php?r=tblSkill/index
HTTP_REFERER=http://localhost/yiitest/index.php?r=site/login
---
2016/08/17 18:20:09 [error] [exception.CException] exception 'CException' with message 'CWebApplication and its behaviors do not have a method or closure named "session_name".' in C:\xampp\htdocs\yii\framework\base\CComponent.php:266
Stack trace:
#0 C:\xampp\htdocs\yiitest\protected\views\layouts\main.php(31): CComponent->__call('session_name', Array)
#1 C:\xampp\htdocs\yiitest\protected\views\layouts\main.php(31): CWebApplication->session_name()
#2 C:\xampp\htdocs\yii\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#4 C:\xampp\htdocs\yii\framework\web\widgets\CContentDecorator.php(76): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#5 C:\xampp\htdocs\yii\framework\web\widgets\CContentDecorator.php(54): CContentDecorator->decorate('<div class="spa...')
#6 C:\xampp\htdocs\yii\framework\web\widgets\COutputProcessor.php(44): CContentDecorator->processOutput('<div class="spa...')
#7 C:\xampp\htdocs\yii\framework\web\CBaseController.php(214): COutputProcessor->run()
#8 C:\xampp\htdocs\yii\framework\web\CBaseController.php(308): CBaseController->endWidget('CContentDecorat...')
#9 C:\xampp\htdocs\yiitest\protected\views\layouts\column2.php(22): CBaseController->endContent()
#10 C:\xampp\htdocs\yii\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#11 C:\xampp\htdocs\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#12 C:\xampp\htdocs\yii\framework\web\CController.php(784): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#13 C:\xampp\htdocs\yiitest\protected\controllers\TblSkillController.php(133): CController->render('index', Array)
#14 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): TblSkillController->actionIndex()
#15 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#16 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#17 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#18 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#19 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#20 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#21 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#22 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#23 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('index')
#24 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('tblSkill/index')
#25 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#26 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#27 {main}
REQUEST_URI=/yiitest/index.php?r=tblSkill/index
HTTP_REFERER=http://localhost/yiitest/index.php?r=site/login
---
2016/08/17 18:29:01 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "test".' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('test')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('test')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('TblSkill/test')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/yiitest/index.php?r=TblSkill/test
HTTP_REFERER=http://localhost/yiitest/index.php?r=tblSkill/index
---
2016/08/17 18:29:02 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "test".' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('test')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('test')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('TblSkill/test')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/yiitest/index.php?r=TblSkill/test
HTTP_REFERER=http://localhost/yiitest/index.php?r=tblSkill/index
---
2016/08/17 18:29:02 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "test".' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('test')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('test')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('TblSkill/test')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/yiitest/index.php?r=TblSkill/test
HTTP_REFERER=http://localhost/yiitest/index.php?r=tblSkill/index
---
2016/08/17 18:29:47 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('test')
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('TblSkill/test')
#9 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/yiitest/index.php?r=TblSkill/test
HTTP_REFERER=http://localhost/yiitest/index.php?r=tblSkill/index
---
2016/08/17 18:32:19 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('AjaxRequest')
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('TblSkill/AjaxRe...')
#9 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/yiitest/index.php?r=TblSkill/AjaxRequest
HTTP_REFERER=http://localhost/yiitest/index.php?r=tblSkill/index
---
2016/08/17 18:32:20 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('AjaxRequest')
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('TblSkill/AjaxRe...')
#9 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/yiitest/index.php?r=TblSkill/AjaxRequest
HTTP_REFERER=http://localhost/yiitest/index.php?r=tblSkill/index
---
2016/08/17 18:32:20 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('AjaxRequest')
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('TblSkill/AjaxRe...')
#9 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/yiitest/index.php?r=TblSkill/AjaxRequest
HTTP_REFERER=http://localhost/yiitest/index.php?r=tblSkill/index
---
2016/08/17 18:32:37 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('AjaxRequest')
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('TblSkill/AjaxRe...')
#9 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/yiitest/index.php?r=TblSkill/AjaxRequest
HTTP_REFERER=http://localhost/yiitest/index.php?r=tblSkill/index
---
2016/08/17 18:32:38 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('AjaxRequest')
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('TblSkill/AjaxRe...')
#9 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/yiitest/index.php?r=TblSkill/AjaxRequest
HTTP_REFERER=http://localhost/yiitest/index.php?r=tblSkill/index
---
2016/08/17 18:32:38 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('AjaxRequest')
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('TblSkill/AjaxRe...')
#9 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/yiitest/index.php?r=TblSkill/AjaxRequest
HTTP_REFERER=http://localhost/yiitest/index.php?r=tblSkill/index
---
2016/08/17 18:36:16 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('AjaxRequest')
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('TblSkill/AjaxRe...')
#9 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/yiitest/index.php?r=TblSkill/AjaxRequest
HTTP_REFERER=http://localhost/yiitest/index.php?r=tblSkill/index
---
2016/08/17 18:37:05 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('AjaxRequest')
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('TblSkill/AjaxRe...')
#9 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/yiitest/index.php?r=TblSkill/AjaxRequest
HTTP_REFERER=http://localhost/yiitest/index.php?r=tblSkill/index
---
2016/08/17 18:37:42 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('AjaxRequest')
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('tblSkill/AjaxRe...')
#9 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/yiitest/index.php?r=tblSkill/AjaxRequest
---
2016/08/17 18:41:53 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('AjaxRequest')
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('tblSkill/AjaxRe...')
#9 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/yiitest/index.php?r=tblSkill/AjaxRequest
---
2016/08/17 18:41:55 [error] [php] Trying to get property of non-object (C:\xampp\htdocs\yiitest\protected\views\tblSkill\index.php:23)
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(869): TblSkillController->renderFile()
#1 C:\xampp\htdocs\yii\framework\web\CController.php(782): TblSkillController->renderPartial()
#2 C:\xampp\htdocs\yiitest\protected\controllers\TblSkillController.php(133): TblSkillController->render()
#3 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): TblSkillController->actionIndex()
#4 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#5 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): TblSkillController->runAction()
#6 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#7 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CAccessControlFilter->filter()
#8 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): TblSkillController->filterAccessControl()
#9 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#10 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#11 C:\xampp\htdocs\yii\framework\web\CController.php(265): TblSkillController->runActionWithFilters()
#12 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): TblSkillController->run()
#13 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#14 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#15 C:\xampp\htdocs\yiitest\index.php(13): CWebApplication->run()
REQUEST_URI=/yiitest/index.php?r=tblSkill/index
in C:\xampp\htdocs\yiitest\protected\views\tblSkill\index.php (23)
in C:\xampp\htdocs\yiitest\protected\controllers\TblSkillController.php (133)
in C:\xampp\htdocs\yiitest\index.php (13)
2016/08/17 18:43:58 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('AjaxRequest')
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('TblSkill/AjaxRe...')
#9 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/yiitest/index.php?r=TblSkill/AjaxRequest
HTTP_REFERER=http://localhost/yiitest/index.php?r=tblSkill/index
---
2016/08/17 18:43:58 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('AjaxRequest')
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('TblSkill/AjaxRe...')
#9 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/yiitest/index.php?r=TblSkill/AjaxRequest
HTTP_REFERER=http://localhost/yiitest/index.php?r=tblSkill/index
---
2016/08/17 18:43:59 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('AjaxRequest')
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('TblSkill/AjaxRe...')
#9 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/yiitest/index.php?r=TblSkill/AjaxRequest
HTTP_REFERER=http://localhost/yiitest/index.php?r=tblSkill/index
---
2016/08/17 18:43:59 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('AjaxRequest')
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('TblSkill/AjaxRe...')
#9 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/yiitest/index.php?r=TblSkill/AjaxRequest
HTTP_REFERER=http://localhost/yiitest/index.php?r=tblSkill/index
---
2016/08/17 18:43:59 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('AjaxRequest')
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('TblSkill/AjaxRe...')
#9 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/yiitest/index.php?r=TblSkill/AjaxRequest
HTTP_REFERER=http://localhost/yiitest/index.php?r=tblSkill/index
---
2016/08/17 18:44:00 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('AjaxRequest')
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('TblSkill/AjaxRe...')
#9 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/yiitest/index.php?r=TblSkill/AjaxRequest
HTTP_REFERER=http://localhost/yiitest/index.php?r=tblSkill/index
---
2016/08/17 18:44:06 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('AjaxRequest')
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('TblSkill/AjaxRe...')
#9 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/yiitest/index.php?r=TblSkill/AjaxRequest
HTTP_REFERER=http://localhost/yiitest/index.php?r=tblSkill/index
---
2016/08/17 18:45:16 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('AjaxRequest')
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('TblSkill/AjaxRe...')
#9 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/yiitest/index.php?r=TblSkill/AjaxRequest
HTTP_REFERER=http://localhost/yiitest/index.php?r=tblSkill/index
---
2016/08/17 18:46:36 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('AjaxRequest')
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('TblSkill/AjaxRe...')
#9 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/yiitest/index.php?r=TblSkill/AjaxRequest
HTTP_REFERER=http://localhost/yiitest/index.php?r=tblSkill/index
---
2016/08/17 18:46:53 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('AjaxRequest')
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('TblSkill/AjaxRe...')
#9 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/yiitest/index.php?r=TblSkill/AjaxRequest
HTTP_REFERER=http://localhost/yiitest/index.php?r=tblSkill/index
---
2016/08/17 19:09:31 [error] [php] Undefined index: foo (C:\xampp\htdocs\yiitest\protected\controllers\TblSkillController.php:141)
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): TblSkillController->runAction()
#1 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#2 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CAccessControlFilter->filter()
#3 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): TblSkillController->filterAccessControl()
#4 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#5 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(265): TblSkillController->runActionWithFilters()
#7 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): TblSkillController->run()
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\yiitest\index.php(13): CWebApplication->run()
REQUEST_URI=/yiitest/index.php?r=TblSkill/AjaxRequest
in C:\xampp\htdocs\yiitest\protected\controllers\TblSkillController.php (141)
in C:\xampp\htdocs\yiitest\index.php (13)
2016/08/17 19:24:40 [error] [php] Undefined variable: id (C:\xampp\htdocs\yiitest\protected\controllers\TblSkillController.php:155)
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): TblSkillController->runAction()
#1 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#2 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CAccessControlFilter->filter()
#3 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): TblSkillController->filterAccessControl()
#4 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#5 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(265): TblSkillController->runActionWithFilters()
#7 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): TblSkillController->run()
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\yiitest\index.php(13): CWebApplication->run()
REQUEST_URI=/yiitest/index.php?r=TblSkill/AjaxRequest
in C:\xampp\htdocs\yiitest\protected\controllers\TblSkillController.php (155)
in C:\xampp\htdocs\yiitest\index.php (13)
2016/08/17 19:28:01 [error] [php] Undefined variable: id (C:\xampp\htdocs\yiitest\protected\controllers\TblSkillController.php:155)
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): TblSkillController->runAction()
#1 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#2 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CAccessControlFilter->filter()
#3 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): TblSkillController->filterAccessControl()
#4 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#5 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(265): TblSkillController->runActionWithFilters()
#7 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): TblSkillController->run()
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\yiitest\index.php(13): CWebApplication->run()
REQUEST_URI=/yiitest/index.php?r=TblSkill/AjaxRequest
in C:\xampp\htdocs\yiitest\protected\controllers\TblSkillController.php (155)
in C:\xampp\htdocs\yiitest\index.php (13)
2016/08/17 19:28:21 [error] [php] Undefined variable: id (C:\xampp\htdocs\yiitest\protected\controllers\TblSkillController.php:155)
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): TblSkillController->runAction()
#1 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#2 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CAccessControlFilter->filter()
#3 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): TblSkillController->filterAccessControl()
#4 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#5 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(265): TblSkillController->runActionWithFilters()
#7 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): TblSkillController->run()
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\yiitest\index.php(13): CWebApplication->run()
REQUEST_URI=/yiitest/index.php?r=TblSkill/AjaxRequest
in C:\xampp\htdocs\yiitest\protected\controllers\TblSkillController.php (155)
in C:\xampp\htdocs\yiitest\index.php (13)
2016/08/17 19:30:49 [error] [php] Undefined variable: id (C:\xampp\htdocs\yiitest\protected\controllers\TblSkillController.php:160)
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): TblSkillController->runAction()
#1 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#2 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CAccessControlFilter->filter()
#3 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): TblSkillController->filterAccessControl()
#4 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#5 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(265): TblSkillController->runActionWithFilters()
#7 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): TblSkillController->run()
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\yiitest\index.php(13): CWebApplication->run()
REQUEST_URI=/yiitest/index.php?r=TblSkill/AjaxRequest
in C:\xampp\htdocs\yiitest\protected\controllers\TblSkillController.php (160)
in C:\xampp\htdocs\yiitest\index.php (13)
2016/08/17 19:41:11 [error] [php] Invalid argument supplied for foreach() (C:\xampp\htdocs\yii\framework\db\schema\CDbCommandBuilder.php:673)
Stack trace:
#0 C:\xampp\htdocs\yiitest\protected\controllers\TblSkillController.php(157): TblSkillController->loadModelSkillOfUser()
#1 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): TblSkillController->actionAjaxClear()
#2 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#3 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): TblSkillController->runAction()
#4 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#5 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CAccessControlFilter->filter()
#6 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): TblSkillController->filterAccessControl()
#7 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#8 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#9 C:\xampp\htdocs\yii\framework\web\CController.php(265): TblSkillController->runActionWithFilters()
#10 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): TblSkillController->run()
#11 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#12 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#13 C:\xampp\htdocs\yiitest\index.php(13): CWebApplication->run()
REQUEST_URI=/yiitest/index.php?r=TblSkill/AjaxClear
in C:\xampp\htdocs\yiitest\protected\controllers\TblSkillController.php (164)
in C:\xampp\htdocs\yiitest\protected\controllers\TblSkillController.php (157)
in C:\xampp\htdocs\yiitest\index.php (13)
2016/08/17 19:43:26 [error] [php] Invalid argument supplied for foreach() (C:\xampp\htdocs\yii\framework\db\schema\CDbCommandBuilder.php:673)
Stack trace:
#0 C:\xampp\htdocs\yiitest\protected\controllers\TblSkillController.php(157): TblSkillController->loadModelSkillOfUser()
#1 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): TblSkillController->actionAjaxClear()
#2 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#3 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): TblSkillController->runAction()
#4 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#5 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CAccessControlFilter->filter()
#6 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): TblSkillController->filterAccessControl()
#7 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#8 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#9 C:\xampp\htdocs\yii\framework\web\CController.php(265): TblSkillController->runActionWithFilters()
#10 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): TblSkillController->run()
#11 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#12 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#13 C:\xampp\htdocs\yiitest\index.php(13): CWebApplication->run()
REQUEST_URI=/yiitest/index.php?r=TblSkill/AjaxClear
in C:\xampp\htdocs\yiitest\protected\controllers\TblSkillController.php (164)
in C:\xampp\htdocs\yiitest\protected\controllers\TblSkillController.php (157)
in C:\xampp\htdocs\yiitest\index.php (13)
2016/08/17 19:46:57 [error] [php] Invalid argument supplied for foreach() (C:\xampp\htdocs\yii\framework\db\schema\CDbCommandBuilder.php:673)
Stack trace:
#0 C:\xampp\htdocs\yiitest\protected\controllers\TblSkillController.php(157): TblSkillController->loadModelSkillOfUser()
#1 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): TblSkillController->actionAjaxClear()
#2 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#3 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): TblSkillController->runAction()
#4 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#5 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CAccessControlFilter->filter()
#6 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): TblSkillController->filterAccessControl()
#7 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#8 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#9 C:\xampp\htdocs\yii\framework\web\CController.php(265): TblSkillController->runActionWithFilters()
#10 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): TblSkillController->run()
#11 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#12 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#13 C:\xampp\htdocs\yiitest\index.php(13): CWebApplication->run()
REQUEST_URI=/yiitest/index.php?r=TblSkill/AjaxClear
in C:\xampp\htdocs\yiitest\protected\controllers\TblSkillController.php (164)
in C:\xampp\htdocs\yiitest\protected\controllers\TblSkillController.php (157)
in C:\xampp\htdocs\yiitest\index.php (13)
2016/08/17 20:05:52 [error] [exception.CException] exception 'CException' with message 'Property "TblSkill.model" is not defined.' in C:\xampp\htdocs\yii\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(145): CComponent->__get('model')
#1 C:\xampp\htdocs\yiitest\protected\controllers\TblSkillController.php(151): CActiveRecord->__get('model')
#2 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): TblSkillController->actionAjaxRequest()
#3 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#5 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#7 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#8 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#9 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#10 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('AjaxRequest')
#12 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('TblSkill/AjaxRe...')
#13 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#14 C:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/yiitest/index.php?r=TblSkill/AjaxRequest
HTTP_REFERER=http://localhost/yiitest/index.php?r=tblSkill/index
---
